databases:
  - name: searchinsights-db
    databaseName: searchinsights
    user: searchinsights
    plan: free

services:
  - type: web
    name: searchinsights
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    branch: master
    healthCheckPath: "/"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: searchinsights-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 1
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: development:test
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: REDIS_URL
        value: redis://localhost:6379

  - type: worker
    name: searchinsights-sidekiq
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec sidekiq"
    plan: free
    branch: master
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: searchinsights-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: development:test
      - key: REDIS_URL
        value: redis://localhost:6379

  - type: redis
    name: searchinsights-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
